app/urls.py
from django.urls import path
from . import views

app_name = "app"

urlpatterns = [
    path('', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('update/', views.update, name="update"),
    path('logout/', views.log_out, name='logout'),
]

base/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
]

app/models.py
from django.db import models

# Create your models here.

app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(
        label="Password",
        widget=forms.PasswordInput(attrs={'class':'form-control', 'type':'password'}))
    password2 = forms.CharField(
        label="Confirm Password",
        widget=forms.PasswordInput(attrs={'class':'form-control', 'type':'password'}))

    def clean_email(self):
        if User.objects.filter(email=self.cleaned_data['email']).exists():
            raise forms.ValidationError("the given email is already registered")
        return self.cleaned_data['email']

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        widgets = {
            'username' : forms.TextInput(attrs={'class': 'form-control'}),
        }


class UpdateForm(forms.ModelForm):
    first_name = forms.CharField(max_length=255, required=False)
    last_name = forms.CharField(max_length=255, required=False)

    class Meta:
        model = User
        fields = ['first_name', 'last_name','email']

app/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from .forms import UserRegistrationForm, UpdateForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import update_session_auth_hash
# from django.contrib.auth.forms import UserCreationForm

# Create your views here.

@login_required
def home(request):
    template_name = 'home.html'
    return render(request, template_name, {})


@login_required
def update(request):
    template_name = 'registration/update.html'
    if request.user.is_authenticated:
        user = request.user
        form = UpdateForm(request.POST, instance = user)
        if request.method == "POST":   
            if form.is_valid():
                form.save()
                update_session_auth_hash(request, form.instance)
                return redirect('/')
            else: 
                return render(request, 'update.html', {'form': form})
        else: 
            form = UpdateForm(instance = user)
        return render(request, template_name, {'form': form})


def register(request):
    if request.user.is_authenticated:
        return redirect('app:home')
    else:
        template_name = 'registration/register.html'
        if request.method == 'POST':
            form = UserRegistrationForm(request.POST)
            if form.is_valid():
                form.save()
                messages.success(request, f'Your account has been created. You can log in now!')
                return redirect('login')
        else:
            form = UserRegistrationForm()

        context = {'form': form}
        return render(request, template_name, context)
    
@login_required
def log_out(request):
    logout(request)
    return redirect('login')

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
    <style>
        body {
            background-color: #fbfbfb;
        }

        @media(min-width: 991.98px) {
            main {
                margin-left: 200px;
                padding: 55px 0 0;
            }
        }

        /* Sidebar */
        .sidebar {
            position: fixed;
            top: 0;
            bottom: 0;
            left: 0;
            padding: 55px 0 0;
            box-shadow: 0 2px 5px 0 rgb(0 0 0 / 5%), 0 2px 10px 0 rgb(0 0 0 / 5%);
            width: 200px;
            z-index: 600;
        }

        @media(max-width: 991.98px) {
            main {
                padding: 55px 0 0;
            }

            .sidebar {
                width: 100%;
            }
        }

        .sidebar .active {
            border-radius: 5px;
            box-shadow: 0 2px 5px 0 rgb(0 0 0 / 16%), 0 2px 10px 0 rgb(0 0 0 / 12%);
        }

        .sidebar-sticky {
            position: relative;
            top: 0;
            height: calc(100vh - 48px);
            padding-top: 0.5rem;
            overflow-x: hidden;
            overflow-y: auto;
        }

        .navbar-brand {
            color: black;
        }
    </style>
</head>

<body>
    {% block content %}{% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>

</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}
Home
{% endblock %}

{% block content %}

<header>

  <nav id="sidebarMenu" class="collapse d-lg-block sidebar bg-white">
    <div class="position-sticky">
      <div class="list-group list-group-flush mx-3 mt-4">
        <a href="" class="list-group-item list-group-item-action py-2" aria-current="true">
          <i class="bi bi-house me-3"></i>
          <span>Home</span>
        </a>
        <a href="" class="list-group-item list-group-item-action py-2" aria-current="true">
          <i class="bi bi-journal me-3"></i>
          <span>Orders</span>
        </a>
        <a href="" class="list-group-item list-group-item-action py-2" aria-current="true">
          <i class="bi bi-bag me-3"></i>
          <span>Products</span>
        </a>
        <a href="" class="list-group-item list-group-item-action py-2" aria-current="true">
          <i class="bi bi-person me-3"></i>
          <span>Customers</span>
        </a>
        <a href="" class="list-group-item list-group-item-action py-2" aria-current="true">
          <i class="bi bi-graph-up me-3"></i>
          <span>Reports</span>
        </a>
        <a href="" class="list-group-item list-group-item-action py-2" aria-current="true">
          <i class="bi bi-layers me-3"></i>
          <span>Integrations</span>
        </a>

      </div>
    </div>
  </nav>
  <!-- Sidebar -->

  <!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-white bg-white fixed-top">
    <!-- Container wrapper -->
    <div class="container-fluid">


      <!-- Brand -->
      <a class="navbar-brand" href="">
        Dashboard
      </a>
      <!-- Search form -->
      <form class="d-none d-md-flex input-group w-auto my-auto align-items-end">
        <input class="form-control border rounded" style="min-width: 225px" placeholder='Search (ctrl + "/" to focus)'
          type="search">
        <span class="input-group-append ps-2">
          <button class="btn bg-white border rounded" type="button">
            Search
          </button>
        </span>
      </form>


      <div class="ms-auto">
        <!-- Avatar -->
        <div class="nav-item dropdown">
          <a class="nav-link hidden-arrow d-flex align-items-center dropdown-toggle" href="" id="navbarDropdownMenuLink"
            type="" data-bs-toggle="dropdown" aria-expanded="false">
            <img src="https://mdbootstrap.com/img/Photos/Avatars/img (31).jpg" class="rounded-circle" height="28" alt=""
              loading="lazy" />
          </a>
          <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuLink">
            <li>
              <a class="dropdown-item" href="{% url 'app:update' %}">Update User</a>
            </li>
            <li>
              <a class="dropdown-item" href="{% url 'password_change' %}">Change Password</a>
            </li>
            <li>
              <a class="dropdown-item" href="{% url 'app:logout' %}">Logout</a>
            </li>
          </ul>
        </div>
      </div>


      <!-- Toggle button -->
      <a class="navbar-toggler" style="color: black;" type="button" data-bs-toggle="collapse"
        data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
        <i class=""><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-list" viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z"/>
</svg></i>
      </a>
    </div>
    <!-- Container wrapper -->
  </nav>
  <!-- Navbar -->
</header>
<!--Main Navigation-->

<!--Main layout-->
<main>
  <div class="container-fluid ms-sm-auto">
    <div class="row">
      <div class="col-md-9 col-lg-9">

        <div class="row">
          <div class="col-sm-6 pt-4">
            <div class="card">
              <div class="card-body">
                <h5 class="card-title">Special title treatment</h5>
                <p class="card-text">With supporting text below as a natural lead-in to additional
                  content.</p>
                <a href="#" class="btn btn-outline-secondary">Go somewhere</a>
              </div>
            </div>
          </div>
          <div class="col-sm-6 pt-4">
            <div class="card">
              <div class="card-body">
                <h5 class="card-title">Special title treatment</h5>
                <p class="card-text">With supporting text below as a natural lead-in to additional
                  content.</p>
                <a href="#" class="btn btn-outline-secondary">Go somewhere</a>
              </div>
            </div>
          </div>
          <div class="col-sm-6 pt-4">
            <div class="card">
              <div class="card-body">
                <h5 class="card-title">Special title treatment</h5>
                <p class="card-text">With supporting text below as a natural lead-in to additional
                  content.</p>
                <a href="#" class="btn btn-outline-secondary">Go somewhere</a>
              </div>
            </div>
          </div>
          <div class="col-sm-6 pt-4">
            <div class="card">
              <div class="card-body">
                <h5 class="card-title">Special title treatment</h5>
                <p class="card-text">With supporting text below as a natural lead-in to additional
                  content.</p>
                <a href="#" class="btn btn-outline-secondary">Go somewhere</a>
              </div>
            </div>
          </div>
        </div>

      </div>
      <div class="col-md-3 col-lg-3 pt-4 pb-5">

        <div class="card">
          <div class="card-header">
            Quote
          </div>
          <div class="card-body">
            <blockquote class="blockquote mb-0">
              <p>A well-known quote, contained in a blockquote element.</p>
              <footer class="blockquote-footer">Someone famous in
                <cite title="Source Title">Source</cite>
              </footer>
            </blockquote>
          </div>
        </div>

      </div>
    </div>
  </div>
</main>
{% endblock %}